fps_settings:
  - 0.2
  - 0.4
  - 0.8
token_settings:
  - 60
  - 90
  - 120
num_samples: 1
num_videos: 5
hf_token: ""
seed: 42
compile: False # activate torch.compile()
# avoid_cache: False (TODO: place some random characters into prompt to avoid cache)
